import { Navbar } from "@/components/navbar";
import { ProjectCard } from "@/components/project-card";
import { projects, roleFits } from "@/components/portfolio-data";
import { WorkflowDiagram } from "@/components/workflow-diagram";

const backgroundHighlights = ["BCBS 239, CCAR, CECL", "Regulatory controls and audit documentation", "Data lineage and validation", "AI-enabled process engineering", "Python, SQL, Power BI, Tableau, Alteryx", "LLM evaluation, counterfactual ablation, agentic workflows"];

export default function Home() {
  return (
    <main id="top">
      <Navbar />
      <section className="hero section-wrap">
        <div className="hero-copy">
          <p className="eyebrow hero-kicker"><span className="status-dot" />Finance controls × AI reliability</p>
          <h1>Rahul Sai<br /><em>Boddapati</em></h1>
          <p className="hero-title">AI Platform &amp; Agentic Systems Portfolio</p>
          <p className="hero-lede">Evaluation, governance, and failure-mode testing for AI decision workflows.</p>
          <p className="hero-intro">I work at the intersection of finance data governance, regulatory controls, LLM evaluation, and agentic workflow validation. My focus is building and testing AI decision systems through counterfactual ablation, adversarial baselines, attribution checks, and reproducible audit trails.</p>
          <p className="hero-closer">I am most useful where AI systems need to be trusted before they are scaled.</p>
          <div className="hero-actions">
            <a href="#work" className="button button-primary">View featured work <span>↓</span></a>
            {/* TODO: Add public/RahulSai_Resume.pdf before publishing. */}
            <a href="/RahulSai_Resume.pdf" className="button">Download resume <span>↓</span></a>
          </div>
          <div className="social-links"><a href="https://github.com/Rahulsai2026" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://linkedin.com/in/rahul-sai-boddapati" target="_blank" rel="noreferrer">LinkedIn ↗</a></div>
        </div>
        <aside className="hero-statement" aria-label="Core professional positioning"><div className="quote-mark">“</div><p>I attack AI decision systems before reality does.</p><span>Core operating position</span></aside>
      </section>
      <section className="credibility section-wrap" aria-label="Professional credibility"><p>Wells Fargo <span>Finance Data Governance &amp; Regulatory Controls</span></p><p>AI Model Validation <span>Counterfactual Ablation &amp; Agent Audits</span></p><p>Agentic Workflows <span>Keel, TPAAM, LLM Evaluation</span></p><p>Focus <span>Trustworthy Decision Systems</span></p></section>
      <section className="section-wrap thesis" aria-labelledby="thesis-title"><div className="section-heading"><p className="eyebrow">01 — Thesis</p><h2 id="thesis-title">Independent Validation of <em>Complex Decision Systems</em></h2></div><div className="thesis-copy"><p>My work is built around a simple question: when a system makes a decision, how do we know it deserves our trust?</p><p>I approach AI systems the same way model validators approach financial controls: test assumptions, isolate failure modes, separate attribution, and document what breaks. My goal is to help build AI systems that are not only powerful, but inspectable, auditable, and reliable under real-world pressure.</p></div><WorkflowDiagram /></section>
      <section id="work" className="section-wrap projects" aria-labelledby="work-title"><div className="section-heading"><p className="eyebrow">02 — Selected work</p><h2 id="work-title">Featured <em>Work</em></h2></div><p className="section-intro">Three systems, one recurring discipline: verify what caused the result before claiming that the system is reliable.</p><div className="project-list">{projects.map((project) => <ProjectCard project={project} key={project.title} />)}</div></section>
      <section id="role-fit" className="section-wrap role-fit" aria-labelledby="role-title"><div className="section-heading"><p className="eyebrow">03 — Role fit</p><h2 id="role-title">Fit for <em>AI Platform Roles</em></h2></div><p className="section-intro">I am most aligned with AI Platform roles involving agent orchestration, evals, context management, guardrails, model gateways, RAG systems, and reliability layers around AI workflows.</p><div className="role-grid">{roleFits.map(([number, title, description]) => <article key={title}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
      <section id="why-me" className="section-wrap strong-fit" aria-labelledby="why-title"><div><p className="eyebrow">04 — Why me</p><h2 id="why-title">Why I&apos;m a <em>Strong Fit</em></h2></div><div className="strong-fit-copy"><p>I bring a finance-control background and an AI-evaluation mindset. At Wells Fargo, I learned regulatory validation, lineage, audit documentation, and control discipline. Independently, I&apos;ve applied the same mindset to LLM agents and agentic workflows through counterfactual ablation, adversarial testing, attribution audits, and failure-mode analysis.</p><p>I&apos;m most useful where AI systems need to be tested, trusted, and turned into reliable workflows. I move quickly, but my default instinct is falsification: build the system, attack the assumptions, separate signal from story, and document what survives.</p><p className="closing-line">I&apos;m excited by AI Platform work because the next major challenge is not just building agents, but making them reliable enough for real users and real decisions.</p></div><blockquote>“I attack AI decision systems before reality does.”</blockquote></section>
      <section className="principle section-wrap" aria-labelledby="principle-title"><div className="section-heading"><p className="eyebrow">05 — Operating principle</p><h2 id="principle-title">Attack the system before <em>reality does.</em></h2></div><p>My strongest work starts from skepticism. I build or inspect a system, then design experiments to prove where it fails. That approach applies across regulatory reporting, LLM agents, trading workflows, and AI product platforms.</p><div className="principle-list"><span>Separate signal from narrative.</span><span>Separate AI action from human intervention.</span><span>Separate claimed reasoning from causal influence.</span></div></section>
      <section id="background" className="section-wrap background" aria-labelledby="background-title"><div className="section-heading"><p className="eyebrow">06 — Background</p><h2 id="background-title">Professional <em>Background</em></h2></div><div><p className="background-lede">Finance professional with 3+ years at Wells Fargo working across regulatory controls, data governance, lineage, and audit-ready validation. Promoted from Associate to Analyst within 1.8 years. Built AI-enabled process tools used by the team, including a regulatory report extraction workflow and a multi-layer GenAI prompt architecture for documentation.</p><ul>{backgroundHighlights.map((highlight) => <li key={highlight}>{highlight}</li>)}</ul></div></section>
      <section id="contact" className="contact section-wrap" aria-labelledby="contact-title"><p className="eyebrow">07 — Contact</p><h2 id="contact-title">Let&apos;s build AI systems<br />that <em>deserve trust.</em></h2><p>I&apos;m interested in AI Platform, LLM evaluation, AI model validation, agentic workflows, AI governance, and product roles where reliability matters.</p><p className="contact-email"><a href="mailto:boddapati.rahul@gmail.com">boddapati.rahul@gmail.com</a></p><div className="contact-actions"><a className="button button-primary" href="mailto:boddapati.rahul@gmail.com">Email Rahul <span>↗</span></a><a className="button" href="https://github.com/Rahulsai2026" target="_blank" rel="noreferrer">GitHub <span>↗</span></a><a className="button" href="https://linkedin.com/in/rahul-sai-boddapati" target="_blank" rel="noreferrer">LinkedIn <span>↗</span></a><a className="button" href="/RahulSai_Resume.pdf">Resume <span>↓</span></a></div></section>
      <footer className="section-wrap"><span>Rahul Sai Boddapati</span><span>Finance Data Governance · Regulatory Controls · AI Model Validation · Agentic Workflows</span><a href="#top">Back to top ↑</a></footer>
    </main>
  );
}
